- name: create ec2 and r53 records
  hosts: all      # if don't use inventory file 
  connection: local

  vars:
   sg_id: sg-02da904f56f6ac0ca
   ami_id: ami-0220d79f3f480ecf5
   domain_name: akviklabs.online
   env: dev  
   instances:
   - mongodb
   - catalogue

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     instance_type: "t3.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     name: "{{ item }}-{{ env }}"
     tags:
      Project: roboshop
      Component: "{{ item }}"
      Environment: "{{ env }}"
      Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"

     # create route53
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #mongodb-dev.akviklabs.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    
